[package]
name = "bridgescope-test-support"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
bridgescope-adb = { path = "../bridgescope-adb" }
bridgescope-domain = { path = "../bridgescope-domain" }
image.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[lints]
workspace = true
