[package]
name = "bridgescope-ai"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
bridgescope-domain = { path = "../bridgescope-domain" }
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true }
tracing.workspace = true
reqwest.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
